<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Scholarship;

class ScholarshipSeeder extends Seeder
{
    public function run(): void
    {
        Scholarship::truncate();

        $rows = [
            [
                'name' => 'IDB Scholarship',
                'category' => 'International',
                'criteria' => 'The fields of study should be in development-related disciplines (focus on Sustainability Science)',
                'award' => 'To pursue undergraduate Professional 4 to 5 yrs bachelor courses in India',
                'eligibility' => '',
                'when_to_apply' => 'August',
                'application' => 'Online',
                //'links' => ['https://medelhi.org/db-scholarship/'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'AICTE Scholarship Scheme for Girl Child / \\',
                'category' => 'Girl Child',
                'criteria' => 'To promote technical education among girls',
                'award' => 'Rs.4000 per Annum (Rs.2000 for Degree and Rs.2000 for Diploma) of up to Rs 50,000 per year per student',
                'eligibility' => 'Two girl child per family, candidate should be admitted to 1st year of Degree/Diploma course in any of The AICTE approved institution, family income less than 8 lakhs',
                'when_to_apply' => '',
                'application' => 'By post, Email',
               // 'links' => ['www.aicte-india.org', 'https://www.aicte-india.org/schemes/students-development-schemes/General-Instructions'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'AICTE- Scholarships for Differently Able (DA) Students/ \\',
                'category' => 'Differently Abled',
                'criteria' => 'To provide the financial assistance to the DA students to promote technical education (Eng, Architecture, Pharmacy, applied arts etc.) at degree and diploma levels',
                'award' => 'Rs.1000 per Annum (Rs. 500 for Degree and Rs.500 for Diploma), up to Rs 50000 per year per student',
                'eligibility' => 'Candidate should be admitted to 1st year of Degree/Diploma course in any of The AICTE approved institution, family income less than 8 lakhs',
                'when_to_apply' => 'October',
                'application' => 'By post, Email',
               // 'links' => ['https://www.buddystudy.com/', 'https://www.aicte-india.org/schemes/students-development-schemes/General-Instructions'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Bharat Petroleum Scholarships',
                'category' => 'Corporate',
                'criteria' => 'Indian citizen, holding a degree from a recognized university and residing in India at the time of application, and who have secured at least 65% in Arts and 70% in Engineering, Science or Commerce at the Graduate Level. The applicant should be below 25 years as on first of September. Students with confirmed admission to any full time, two years Post Graduate Degree Course (in any field of education other than fine arts), at any recognized University/ Institute of repute in India or abroad.',
                'award' => '',
                'eligibility' => 'Secured at least 65% in Arts and 70% in Engineering, Science or Commerce at the Graduate level. The applicant should be below 25 years as on First of September.',
                'when_to_apply' => 'The official notification is released much before the normal academic year in India and abroad based institutions and Universities.',
                'application' => 'Online/Form can be obtained from the organization by sending them a request for the application form in a self addressed envelope affixed with a stamp of appropriate value before the last date for obtaining the application form',
                //'links' => ['bharatpetroleum.com', 'https://www.bharatpetroleum.com/careers/Scholarship-Announcement.aspx'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'CBSE Single Girl Child Scholarship for Class 10 passed only single girl child of their Parents/ CBSE Merit Scholarship Scheme For Single Girl Child',
                'category' => 'Girl Child',
                'criteria' => 'Studying Class XI & XII in School (affiliated with CBSE) whose tuition fee is not more than Rs. 1,500/- p.m. during the academic year',
                'award' => 'Rs 500 per month for 2 years (maximum)',
                'eligibility' => 'All Single Girl Students, who have secured 60% or more marks in CBSE Class X Examination',
                'when_to_apply' => 'Last date for the submission of Application Form: October',
                'application' => 'Online',
               // 'links' => ['http://cbse.nic.in/Scholarship/Webpages/Guidelines%20and%20AF.html'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Central Sector Scheme / Central Sector Scheme of Scholarship for College and University Students',
                'category' => 'Central Government',
                'criteria' => 'Scholarship for Class 12 passed students of Science, Commerce & Arts subjects. Annual target is 82000 scholarships per year (41000 for boys and 41000 for girls)',
                'award' => 'Graduation course: Rs 10,000 per year for 3 years, Master courses: Rs 20,000 per year for next 2 years',
                'eligibility' => 'Students above 80th percentile of successful candidates in the relevant stream from a particular Board of Examination in class XII, pursuing regular course and not availing other scholarships, are eligible to apply under this Scheme.',
                'when_to_apply' => 'Application Start Date: First week of July Last Date for Submission of Application form: Last Week of August',
                'application' => 'Online, post',
                //'links' => ['http://mhrd.gov.in/scholarships-education-loan-0'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Chief Minister Relief Fund Scholarship',
                'category' => 'State Government',
                'criteria' => 'Assistance from Chief Minister\'s Relief Fund and Chief Minister\'s Discretionary Fund is given to the economically weaker students. Who is studying in any institutions of the State after passing out the State Board / Council of Secondary Education or a State aided University in West Bengal.',
                'award' => 'Rs 10,000',
                'eligibility' => 'Who has got 65% marks in aggregate in Madhyamik Examination [for H.S. level] or 60% in aggregate in H.S. Examination [for U.G. level] or 55% Marks in the Honours Subject [for PG. level] Annual family income not exceed Rs 60,000/- .',
                'when_to_apply' => 'There are no exact/fixed date to apply for this Scholarship. Candidates are eligible to apply at any time during his/her current course.',
                'application' => 'Online/ Downloaded Application to be send by Ordinary Post/Drop box to the Address of – The Assistant Secretary, Chief Minister\'s Office, \'Nabanna\' 325, Sarat Chatterjee Road Howrah - 711 102',
               // 'links' => ['http://wbcmo.gov.in/donation.aspx', 'www.wbcmo.gov.in'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Nest-Junior Scholarships',
                'category' => 'Science & Research',
                'criteria' => 'Students of all recognized schools/ colleges of Class IX, X, XI & XII (Science Stream only) for the award of several scholarships worth Rs. 25,000/- to Rs. 50,000/- each.',
                'award' => 'Rs. 25,000/- to Rs. 50,000/-',
                'eligibility' => 'FOR STUDENTS OF CLASS IX, X, XI & XII (SCIENCE) AND 1ST & 2ND YEAR OF DIPLOMA ENGINEERING',
                'when_to_apply' => 'Last Date for Submission of Application form: 30th April Online Exam Date: End of July NEST Junior Result: 1st Week of September',
                'application' => 'Download application form and sent via post',
               // 'links' => ['www.nest.net.in', 'http://www.nest.net.in/application_form.htm'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'NEST Scholarship 21th Nationwide Education and Scholarship Test (NEST-Senior)',
                'category' => 'Science & Research',
                'criteria' => 'Students of science, engineering and medical courses as well as those in class XII having science',
                'award' => 'NEST SENIOR-I (10 or more scholarships of Rs. 35,000/- each with Rs. 75,000/- to Rank No. 1)',
                'eligibility' => 'Students pursuing science subject specialization in Class XII and Bachelors level.',
                'when_to_apply' => 'Last Date Of Submission Of Application Forms: 31st October, 2018. Exam Date: Last Sunday Of January. NEST Senior Result: 5 April, 2019.',
                'application' => 'Online(application) and through post (demand draft)',
               // 'links' => ['www.nest.net.in', 'http://www.nest.net.in/ application_form.htm'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Foundation for Excellence Scholarship (FFE)',
                'category' => 'Private',
                'criteria' => 'The applicants should have passed their Higher Secondary/Pre-University Intermediate/CBSE/ISC or equivalent board qualifying examination not earlier than in 2017.',
                'award' => '',
                'eligibility' => 'The applicants should have scored not less than 70% marks in the qualifying examination. Students for their degrees in Engineering, Technology (BE/BTech) and Medicine (MBBS)',
                'when_to_apply' => '',
                'application' => 'Online',
               // 'links' => ['www.ffe.org', 'https://www.buddy4study.com/UID/ FFES'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'G. P. BIRLA SCHOLARSHIP',
                'category' => 'Private',
                'criteria' => 'G.P. Birla Educational scholarships to the students who are recently passed Higher Secondary Examination',
                'award' => 'Rs. 50,000/- per student per year',
                'eligibility' => '12th Passed, 80% + marks in state board or 85% or more from Central Board, studies may be in any stream including Science, Humanities, Engineering, Medicine, Architecture, Commerce, Law, Chartered Accountancy, Company Secretaryship and Cost Accountancy Course in any recognized University/ Institution in India',
                'when_to_apply' => 'Last Date for Submission of Application form: July',
                'application' => 'Download application and then sent via post',
               // 'links' => ['http://www.gpbirlaedufoundation.com/'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Gaurav Foundation Scholarship',
                'category' => 'Private',
                'criteria' => 'Class 12th passed or above students going for higher education',
                'award' => 'Tuition fee assistance up to INR 10 Lac to deserving candidates',
                'eligibility' => 'Age group of 17 years to 36 years Have scored minimum 60% marks in all exams (since school days)',
                'when_to_apply' => 'Application Start Date:31st October, 2018',
                'application' => 'Download application and then sent via post',
               // 'links' => ['https://www.buddy4study.com/UID/ GFMS', 'http://www.gauravfoundation.org/scholarship.html'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'HDFC Scholarship',
                'category' => 'Corporate',
                'criteria' => 'ECSS aims to cover students from recognized Private or Government aided schools between standards 6 and 12 and students studying in undergraduate and post-graduate courses (full-time/part-time degree/ diplomat/courses) who due to personal/family crises are unable to continue bearing the cost of education and are at risk of dropping out of school/college/ university. This situation would be defined as bereavement/death/ terminal illness/ permanent disability and loss of job of the breadwinner due to accident or any such extreme circumstances that have put a strain on the family resources.',
                'award' => 'The Scholarship will cover the total annual School Fee upto a maximum of Rs 10,000 and College/ University Fee upto a maximum of Rs 25,000 of the selected candidates.',
                'eligibility' => 'Application window open from: 1st July Last Date for Submission of Application form: August Scholarship Selected List will be available: November',
                'when_to_apply' => '',
                'application' => 'Online/Offline',
               // 'links' => ['https://www.hdfcbank.com/htdocs/common/ECSS_scholarship.htm'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Indian Oil academic Scholarship for Class 10, 12 & ITI passed students',
                'category' => 'Corporate',
                'criteria' => 'Total 2,600 Scholarships',
                'award' => 'IndianOil Educational Scholarship is awarded for 4 streams as per detail given below : Engineering: 48 months @ 3000 Per month MBBS: 48 months @ 3000 Per month MBA: 24 months @ 3000 Per month 10+/ITI : 24 months @ 1000 Per month',
                'eligibility' => 'Course 10th/12th/ITI, Engineering & MBBS, MBA',
                'when_to_apply' => 'One can apply for the scholarship from 1st September to 30th September of every year. Submit Their Required Documents By 31st October',
                'application' => 'Online',
              //  'links' => ['http://foclscholarship.sgm4u.in/index.php', 'www.foci.com'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Internshala-career Scholarship for Girls',
                'category' => 'Girl Child',
                'criteria' => 'The scholarship is meant to advance the girl\'s career in some way – be it an allowance for pursuing an internship or undertaking a project in the chosen field, payment towards a specialized training program, special equipment, etc.',
                'award' => 'Rs 25,000',
                'eligibility' => 'Any girl (an Indian national) between the ages of 17 to 23 years (as of 31st December 2016), i.e. born between 1st January 1993 and 31st December 1999 with a career objective is eligible to apply',
                'when_to_apply' => '',
                'application' => 'Online',
               // 'links' => ['internshala.com', 'https://blog.internshala.com/2017/12/ internshala-career-scholarship-for-girls-2018/'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Jagdish Bose National Science Talent Search (JBNSTS) Junior talent search test',
                'category' => 'Science & Research',
                'criteria' => 'The students who have passed their 10th standard or equivalent examinations with 75% marks in aggregate and taken admission in class XI in science streams (with at least 3 subjects from Physics, Chemistry, Mathematics, Biology, Statistics and Computer Science) in the year of application. It is a bi-phasic test involving written test (1st Phase) and interview (Final Phase).',
                'award' => 'Varies',
                'eligibility' => 'Any Indian National who has passed the Higher Secondary or equivalent examination in the year of application (i.e., current year) and is studying B.Sc. (Hons.), Engineering or Medicine at undergraduate level in any institution, registered in West Bengal.',
                'when_to_apply' => 'Online & Offline Application Starter: 1st June, Last Date for Submission of Application form: July, Last Date of Issue of Admit Card: August, Written Test: August, JBNSTS Junior Talent Search Test Result: November',
                'application' => 'Download application and then sent via post',
               // 'links' => ['www.jbnsts.org', 'https://www.jbnsts.org/ juschprg.php'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'JM SETHA MERIT SCHOLARSHIP SCHEME',
                'category' => 'Private',
                'criteria' => 'The Scholarship scheme is categorized in four groups: Category A - For pursuing class 9 & 10 Category B - For pursuing class 11& 12 Category C- For pursuing any undergraduate course Category D- For pursuing any post-graduate course.',
                'award' => 'Category A (No. o Scholarships 15) - Rs. 400 p.m. for two years Category B (No. o Scholarships 15) - Rs. 500 p.m. for two years Category C (No. o Scholarships 10) - Rs. 600 p.m. for three years as applicable Category D (No. o Scholarships 10) - Rs. 700 p.m. for two or three years as applicable',
                'eligibility' => 'Class 9 to 12, graduation, post graduation',
                'when_to_apply' => 'Date for Submission of Application Form - April to July; Date of Selection of Candidate - August and Date of Disbursement of Scholarship - September OR within the month prior to the next quarter.',
                'application' => 'Download application and then sent via post',
               // 'links' => ['www.b4s.in/UID/JMSMSS', 'http://www.jmstrust.com/activities.aspx'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'KC Mahindra Scholarship scheme',
                'category' => 'Corporate',
                'criteria' => 'KC Mahindra group providing scholarship for students who are took admission on diploma Courses in India.',
                'award' => 'Types of Scholarships: K. C. Mahindra Scholarships for Post-Graduate Studies Abroad Mahindra Search for Talent Scholarship K.C. Mahindra UWC Scholarship Mahindra All India Talent Scholarship (MATIS)',
                'eligibility' => '',
                'when_to_apply' => 'Application Start Date: End of January, 2018 Application End Date: 15th April, 2018',
                'application' => 'Offline',
              //  'links' => ['www.mahindra.com', 'https://www.kcmet.org/what-we-do-Scholarship-Grants.aspx'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'Kishore Vaidyanik Protashambjana (KVPY)',
                'category' => 'Science & Research',
                'criteria' => 'The KVPY Fellowships are given to Indian Nationals only to Study in India',
                'award' => 'Rs 5,000 pm',
                'eligibility' => 'Students enrolled in an undergraduate course in Basic Sciences, that is, B.Sc./B.S./B.Stat./ B.Math./Int. M.Sc./ M.S. in Chemistry, Physics, Mathematics, Statistics, Biochemistry, Microbiology, Cell Biology, Ecology, Molecular Biology, Botany, Zoology, Physiology, Biotechnology, Neurosciences, Bioinformatics, Marine Biology, Geology, Human Biology, Genetics, Biomedical Sciences, Applied Physics, Geophysics, Materials Science or Environmental Science.',
                'when_to_apply' => 'Online Application Starts: 2nd week of July Last Date for Submission of Application form: 2nd Week of August, Last Date of Issue of Admit Card: 2nd Week of October, Exam Date: 1st Week of November, Result Announcement: 2rd Week of December,',
                'application' => 'Online',
               // 'links' => ['http://kvpy.lisc.ernet.in'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'LIC India Scholarship Scheme',
                'category' => 'Corporate',
                'criteria' => 'Students who have passed Class XII exam or the equivalent and are interested to pursue higher education in the field of Vocational Courses through Government recognized Colleges/ Institutes or courses in Industrial Training Institutes (ITI).',
                'award' => 'An amount of Rs. 10,000/- per annum will be awarded to the selected candidate which is payable in ten monthly installments of Rs. 1,000/- each',
                'eligibility' => 'Students who passed the examination with at least 60% marks and the annual family income not more than 1 lakh.',
                'when_to_apply' => 'Apply ASAP:',
                'application' => 'Online',
              //  'links' => ['www.licindia.in', 'https://www.licindia.in/ Bottom-Links/Golden-Jubilee-Foundation/Scholarship'],
                'sort_order' => 0,
                'is_active' => true,
            ],
            [
                'name' => 'For Young Women in Science',
                'category' => 'Girl Child',
                'criteria' => '',
                'award' => 'Cash Rs 2.5 lakh to each girl,',
                'eligibility' => 'Passed XII with min 85% PCM/PCB, Max 19 years, family income should be less than 4 lakh per annum',
                'when_to_apply' => 'Applicants should visit http://www.foryoung.womeninscience.com/',
                'application' => 'Download application and then sent via post',
               // 'links' => ['http://www.foryoungwomeninscience.com/'],
                'sort_order' => 0,
                'is_active' => true,
            ],
        ];

        Scholarship::insert($rows);
    }
}
